name: Mobile CI

on:
  push:
    paths:
      - 'apps/mobile/**'
      - '.github/workflows/mobile-ci.yml'
      - '.eslintrc.json'
      - 'tsconfig.json'
  pull_request:
    paths:
      - 'apps/mobile/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install root deps
        run: npm ci
      - name: Install mobile deps
        working-directory: apps/mobile
        run: npm ci
      - name: Typecheck (mobile)
        working-directory: apps/mobile
        run: npx tsc -p . --noEmit
      - name: Lint (mobile)
        run: npm run mobile:lint
      - name: Jest (mobile)
        working-directory: apps/mobile
        run: npx jest --ci --passWithNoTests

      - name: Set up Java for Android tools
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Detox Android smoke
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          ram-size: 2048M
          disk-size: 4096M
          script: |
            cd apps/mobile
            npm run detox:build
            npm run detox:test
